## Get requests:

GET http://localhost:3000/users/5432
?limit=10
&page=1




## POST Requests
POST http://localhost:3000/users/
Content-Type: application/json

{
    "name": "Hadi",
    "email": "hadi@sazib.com",
    "password": "password"
}
