## Get requests:

GET http://localhost:3000/users/
?limit=10
&page=1




## POST Requests
POST http://localhost:3000/users/
Content-Type: application/json

{
    "firstName": "Sazib",
    "lastName": "Hadi",
    "email": "hadi@sazib.com",
    "password": "password$123",
    "isAuth": true
}
