## Get requests:

GET http://localhost:3000/users/
?limit=10
&page=1




## POST Requests
POST http://localhost:3000/users/
Content-Type: application/json

{
    "firstName": "jamal",
    "lastName": "bhuiyan",
    "email": "jamal@bhuiyan.com",
    "password": "password$123"
}

// Create many users
POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoiamFtYWxAYmh1aXlhbi5jb20iLCJpYXQiOjE3NzU0NzE4ODMsImV4cCI6MTc3NTQ3NTQ4MywiYXVkIjoibG9jYWxob3N0OiAzMDAwIiwiaXNzIjoibG9jYWxob3N0OiAzMDAwIn0.DP_odpNYWIGneYvZu_7qKhTDONoi-T6aaTTu6HyvigA
{
    "users": [
        {
            "firstName": "Mark",
            "lastName": "Doe",
            "email": "mark@doe.com",
            "password": "password$123"
        },
        {
            "firstName": "Jane",
            "lastName": "Smith",
            "email": "jane@smith.com",
            "password": "password$123"
        }
    ]
}



## Patch Requests
PATCH http://localhost:3000/users/
Content-Type: application/json

{
    "firstName": "Sazib",
    // "lastName": "Hadi",
    "email": "hadi@sazib.com"
    // "password": "password$123"
}
